name: Deploy PR previews

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set BASE_PATH for PR Preview
        if: github.event_name == 'pull_request'
        run: echo "NEXT_PUBLIC_BASE_PATH=/pr-preview/pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          npm ci
          npm run build
          touch out/.nojekyll

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.6
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          source-dir: out
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto